services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "8081:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: ${WEBPASSWORD}
      PIHOLE_DNS_: 9.9.9.9;8.8.8.8;1.1.1.1;8.8.4.4
      DNSSEC: true
      DHCP_ACTIVE: false
      WEBTHEME: default-dark
    # Volumes store your data between container upgrades
    volumes:
      #- './etc-pihole:/etc/pihole'
      - etc:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    networks:
      pihole:
        ipv4_address: 10.8.1.2
      traefik_proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`${HOSTNAME}`)"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.pihole.entrypoints=https"
      - "traefik.http.routers.pihole.tls.certresolver=production"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"

volumes:
  etc:

networks:
  pihole:
    ipam:
      config:
        - subnet: 10.8.1.0/24
  traefik_proxy:
    external: true